





VPATH += $(GENOS)/cpu/$(CPU)/ 
VPATH += $(GENOS)/cpu/$(CPU)/drv/video_page/

CPUSRC := regread.cpp isr.cpp
CPUSRCS := boot.S   cpu_interrupt.S

CPUOBJ := $(CPUSRC:%.cpp=$(OBJDIR)/%.o) 
CPUOBJ += $(CPUSRCS:%.S=$(OBJDIR)/%.o)

PLATFORMOBJ += $(CPUOBJ)
