





VPATH += $(GENOS)/cpu/$(CPU)/ 
VPATH += $(GENOS)/cpu/$(CPU)/drv/video_page/

CPUSRC := video_page.cpp
CPUSRCS := boot.S 

CPUOBJ := $(CPUSRC:%.cpp=$(OBJDIR)/%.o) 
CPUOBJ += $(CPUSRCS:%.S=$(OBJDIR)/%.o)

PLATFORMOBJ += $(CPUOBJ)
