
ifndef GENOS
  ${error GENOS not defined! You must specify where GENOS resides}
endif

ifndef TARGET
  ${error TARGET not defined! You must specify where TARGET resides}
endif

GENOSFLAGS:= -I$(GENOS)/invariant -I$(GENOS)/invariant/prototype
